CREATE DATABASE IF NOT EXISTS `covid` DEFAULT character set utf8 COLLATE utf8_general_ci;
USE `covid`

CREATE TABLE IF NOT EXISTS `covid` (
	`ID` INT(11) NOT NULL,
    `Updated` DATE,
    `Confirmed` INT(11),
    `ConfirmedChange` FLOAT,
    `Deaths` FLOAT,
    `DeathsChange` FLOAT,
    `Recovered` FLOAT,
    `RecoveredChange` FLOAT,
    `Latitude` FLOAT,
	`Longitude` FLOAT,
    `ISO2` VARCHAR(20),
    `ISO3` VARCHAR(20),
    `Country_Region` VARCHAR(50),
    `AdminRegion1` VARCHAR(50),
    `AdminRegion2` VARCHAR(50),
    PRIMARY KEY (`ID`)
) ENGINE = InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `raw_data`;
    
    
 --Preliminary analysis--    
SELECT * FROM `covid` LIMIT 10;

SELECT SUM(Confirmed)AS TOTAL_CONFIRMED_CASES,SUM(Deaths) AS TOTAL_DEATHS,SUM(Recovered) AS TOTAL_RECOVERY_CASES FROM `covid`;
SELECT SUM(Confirmed) AS TOTAL_CONFIRMED_CASES,SUM(Deaths) AS TOTAL_DEATHS,SUM(Recovered) AS TOTAL_RECOVERY_CASES FROM `covid` WHERE `ISO2` = 'US';

SELECT Updated,SUM(CONFIRMED)AS TOTAL_CONFIRMED,SUM(DEATHS) AS TOTAL_DEATHS,SUM(Recovered) AS TOTAL_RECOVERY_CASES FROM `covid` GROUP BY Updated ORDER BY Updated DESC;
SELECT AdminRegion1,SUM(CONFIRMED)AS TOTAL_CONFIRMED,SUM(DEATHS) AS TOTAL_DEATHS,SUM(Recovered) AS TOTAL_RECOVERY_CASES FROM `covid` GROUP BY AdminRegion1 ORDER BY 2 DESC;
SELECT Country_Region,SUM(CONFIRMED)AS TOTAL_CONFIRMED,SUM(DEATHS) AS TOTAL_DEATHS,SUM(Recovered) AS TOTAL_RECOVERY_CASES FROM `covid` GROUP BY Country_Region ORDER BY 2 DESC;


SELECT ISO2,SUM(CONFIRMED)AS TOTAL_CONFIRMED,SUM(DEATHS) AS TOTAL_DEATHS FROM `covid` GROUP BY ISO2 ORDER BY ISO2 ASC;

SELECT monthname(Updated),SUM(CONFIRMED)AS TOTAL_CONFIRMED,SUM(DEATHS) AS TOTAL_DEATHS FROM `covid` GROUP BY monthname(Updated) ORDER BY month(Updated) ASC;